export const linkForCard = 'https://rs-lang-mlatysheva.herokuapp.com/';
export const arrGroup = [0, 1, 2, 3, 4, 5];
export const NUMBER_OF_ANSWERS_PER_QUESTION = 4;
export const PAGES_PER_GROUP = 30;
export const WORDS_PER_PAGE = 20;
export const NUMBER_DIFFERENT_GROUP = 6;
export const UNSWERS_PER_GAME = 10;
export const NUM_TRUE_UNSWERS_IN_GAME_TO_BE_LEARNED = 2;
export const ALL_WORDS = 4000;
