[
  {
  id: "5e9f5ee35eb9e72bc21af4dc",
  group: 0,
  page: 3,
  word: "appropriate",
  image: "files/04_0061.jpg",
  audio: "files/04_0061.mp3",
  audioMeaning: "files/04_0061_meaning.mp3",
  audioExample: "files/04_0061_example.mp3",
  textMeaning: "When a thing is <i>appropriate</i>, it is right or normal.",
  textExample: "It’s <b>appropriate</b> to wear a suit when you go to the office.",
  transcription: "[əpróuprièit]",
  textExampleTranslate: "Уместно носить костюм, когда вы идете в офис",
  textMeaningTranslate: "Когда вещь уместна, она правильная или нормальная",
  wordTranslate: "подходящее"
  },
  {
  id: "5e9f5ee35eb9e72bc21af4dd",
  group: 0,
  page: 3,
  word: "avoid",
  image: "files/04_0062.jpg",
  audio: "files/04_0062.mp3",
  audioMeaning: "files/04_0062_meaning.mp3",
  audioExample: "files/04_0062_example.mp3",
  textMeaning: "To <i>avoid</i> something is to stay away from it.",
  textExample: "<b>Avoid</b> the broken bottle on the floor.",
  transcription: "[əvɔ́id]",
  textExampleTranslate: "Избегайте разбитой бутылки на полу",
  textMeaningTranslate: "Избегать чего-либо - значит держаться подальше от этого",
  wordTranslate: "избегать"
  },
  {
  id: "5e9f5ee35eb9e72bc21af4de",
  group: 0,
  page: 3,
  word: "behave",
  image: "files/04_0063.jpg",
  audio: "files/04_0063.mp3",
  audioMeaning: "files/04_0063_meaning.mp3",
  audioExample: "files/04_0063_example.mp3",
  textMeaning: "To <i>behave</i> is to act in a particular way, especially to be good.",
  textExample: "She always <b>behaves</b> well when her father is around.",
  transcription: "[bihéiv]",
  textExampleTranslate: "Она всегда ведет себя хорошо, когда ее отец рядом",
  textMeaningTranslate: "Вести себя - значит действовать определенным образом, особенно быть хорошим",
  wordTranslate: "вести себя"
  },
  {
  id: "5e9f5ee35eb9e72bc21af4df",
  group: 0,
  page: 3,
  word: "calm",
  image: "files/04_0064.jpg",
  audio: "files/04_0064.mp3",
  audioMeaning: "files/04_0064_meaning.mp3",
  audioExample: "files/04_0064_example.mp3",
  textMeaning: "When someone is <i>calm</i>, they do not get excited or upset.",
  textExample: "A nice warm bath makes me feel so <b>calm</b>.",
  transcription: "[kɑːm]",
  textExampleTranslate: "Хорошая теплая ванна заставляет меня чувствовать себя так спокойно",
  textMeaningTranslate: "Когда кто-то спокоен, он не волнуется и не расстраивается",
  wordTranslate: "спокойный"
  },
  {
  id: "5e9f5ee35eb9e72bc21af4e0",
  group: 0,
  page: 3,
  word: "concern",
  image: "files/04_0065.jpg",
  audio: "files/04_0065.mp3",
  audioMeaning: "files/04_0065_meaning.mp3",
  audioExample: "files/04_0065_example.mp3",
  textMeaning: "<i>Concern</i> is a feeling of worry.",
  textExample: "I was filled with <b>concern</b> after reading the newspaper.",
  transcription: "[kənsə́ːrn]",
  textExampleTranslate: "Я был полон беспокойства после прочтения газеты",
  textMeaningTranslate: "Беспокойство - это чувство беспокойства",
  wordTranslate: "беспокойство"
  },
  {
  id: "5e9f5ee35eb9e72bc21af4e1",
  group: 0,
  page: 3,
  word: "content",
  image: "files/04_0066.jpg",
  audio: "files/04_0066.mp3",
  audioMeaning: "files/04_0066_meaning.mp3",
  audioExample: "files/04_0066_example.mp3",
  textMeaning: "To be <i>content</i> is to be happy and not want more.",
  textExample: "The baby looked very <b>content</b> sitting on the floor.",
  transcription: "[kəntént]",
  textExampleTranslate: "Ребенок выглядел очень довольным, сидя на полу",
  textMeaningTranslate: "Быть довольным значит быть счастливым и не хотеть большего",
  wordTranslate: "содержание"
  },
  {
  id: "5e9f5ee35eb9e72bc21af4e2",
  group: 0,
  page: 3,
  word: "expect",
  image: "files/04_0067.jpg",
  audio: "files/04_0067.mp3",
  audioMeaning: "files/04_0067_meaning.mp3",
  audioExample: "files/04_0067_example.mp3",
  textMeaning: "If you <i>expect</i> something to happen, you believe it will happen.",
  textExample: "I <b>expect</b> the bus to be here very soon.",
  transcription: "[ikspékt]",
  textExampleTranslate: "Я ожидаю, что автобус будет здесь очень скоро",
  textMeaningTranslate: "Если вы ожидаете, что что-то случится, вы верите, что это произойдет",
  wordTranslate: "ожидать"
  },
  {
  id: "5e9f5ee35eb9e72bc21af4e3",
  group: 0,
  page: 3,
  word: "frequently",
  image: "files/04_0068.jpg",
  audio: "files/04_0068.mp3",
  audioMeaning: "files/04_0068_meaning.mp3",
  audioExample: "files/04_0068_example.mp3",
  textMeaning: "When something happens <i>frequently</i>, it happens often.",
  textExample: "We meet <b>frequently</b>, either at the beginning or end of the week.",
  transcription: "[fríːkwəntli]",
  textExampleTranslate: "Мы часто встречаемся, либо в начале, либо в конце недели",
  textMeaningTranslate: "Когда что-то случается часто, это случается часто",
  wordTranslate: "часто"
  },
  {
  id: "5e9f5ee35eb9e72bc21af4e4",
  group: 0,
  page: 3,
  word: "habit",
  image: "files/04_0069.jpg",
  audio: "files/04_0069.mp3",
  audioMeaning: "files/04_0069_meaning.mp3",
  audioExample: "files/04_0069_example.mp3",
  textMeaning: "A <i>habit</i> is a thing that you do often.",
  textExample: "Smoking is a bad <b>habit</b> that can kill you.",
  transcription: "[hǽbit]",
  textExampleTranslate: "Курение - это вредная привычка, которая может тебя убить",
  textMeaningTranslate: "Привычка - это то, что вы часто делаете",
  wordTranslate: "привычка"
  },
  {
  id: "5e9f5ee35eb9e72bc21af4e5",
  group: 0,
  page: 3,
  word: "instruct",
  image: "files/04_0070.jpg",
  audio: "files/04_0070.mp3",
  audioMeaning: "files/04_0070_meaning.mp3",
  audioExample: "files/04_0070_example.mp3",
  textMeaning: "To <i>instruct</i> is to teach.",
  textExample: "My teacher <b>instructs</b> us in several subjects.",
  transcription: "[instrʌ́kt]",
  textExampleTranslate: "Мой учитель учит нас нескольким предметам",
  textMeaningTranslate: "Обучать - значит учить",
  wordTranslate: "инструктирует"
  },
  {
  id: "5e9f5ee35eb9e72bc21af4e6",
  group: 0,
  page: 3,
  word: "issue",
  image: "files/04_0071.jpg",
  audio: "files/04_0071.mp3",
  audioMeaning: "files/04_0071_meaning.mp3",
  audioExample: "files/04_0071_example.mp3",
  textMeaning: "An <i>issue</i> is an important topic.",
  textExample: "The men spoke about <b>issues</b> that were important to the people.",
  transcription: "[íʃuː]",
  textExampleTranslate: "Мужчины говорили о проблемах, которые были важны для людей",
  textMeaningTranslate: "Проблема - важная тема",
  wordTranslate: "проблема"
  },
  {
  id: "5e9f5ee35eb9e72bc21af4e7",
  group: 0,
  page: 3,
  word: "none",
  image: "files/04_0072.jpg",
  audio: "files/04_0072.mp3",
  audioMeaning: "files/04_0072_meaning.mp3",
  audioExample: "files/04_0072_example.mp3",
  textMeaning: "<i>None</i> means not any of something.",
  textExample: "He spent all his money. There is <b>none</b> left.",
  transcription: "[nʌn]",
  textExampleTranslate: "Он потратил все свои деньги. Там ничего не осталось",
  textMeaningTranslate: "Никто не означает не что-то",
  wordTranslate: "никто"
  },
  {
  id: "5e9f5ee35eb9e72bc21af4e8",
  group: 0,
  page: 3,
  word: "patient",
  image: "files/04_0073.jpg",
  audio: "files/04_0073.mp3",
  audioMeaning: "files/04_0073_meaning.mp3",
  audioExample: "files/04_0073_example.mp3",
  textMeaning: "If people are <i>patient</i>, they don’t become angry or upset easily.",
  textExample: "I had to be <b>patient</b> and wait until 5 o’clock to leave.",
  transcription: "[péiʃənt]",
  textExampleTranslate: "Я должен был быть терпеливым и ждать, пока 5 часов, чтобы уйти",
  textMeaningTranslate: "Если люди терпеливы, они не сердятся и не расстраиваются",
  wordTranslate: "пациент"
  },
  {
  id: "5e9f5ee35eb9e72bc21af4e9",
  group: 0,
  page: 3,
  word: "positive",
  image: "files/04_0074.jpg",
  audio: "files/04_0074.mp3",
  audioMeaning: "files/04_0074_meaning.mp3",
  audioExample: "files/04_0074_example.mp3",
  textMeaning: "If something is <i>positive</i>, it is good.",
  textExample: "She has a <b>positive</b> future ahead of her after finishing college.",
  transcription: "[pɑ́zətiv]",
  textExampleTranslate: "У нее впереди хорошее будущее после окончания колледжа",
  textMeaningTranslate: "Если что-то положительное, это хорошо",
  wordTranslate: "позитивный"
  },
  {
  id: "5e9f5ee35eb9e72bc21af4ea",
  group: 0,
  page: 3,
  word: "punish",
  image: "files/04_0075.jpg",
  audio: "files/04_0075.mp3",
  audioMeaning: "files/04_0075_meaning.mp3",
  audioExample: "files/04_0075_example.mp3",
  textMeaning: "To <i>punish</i> means to make someone suffer for breaking the rules or laws.",
  textExample: "To <b>punish</b> me, my teacher had me stand in the corner.",
  transcription: "[pʌ́niʃ]",
  textExampleTranslate: "Чтобы наказать меня, мой учитель заставил меня встать в углу",
  textMeaningTranslate: "Наказать значит заставить кого-то страдать за нарушение правил или законов",
  wordTranslate: "наказать"
  },
  {
  id: "5e9f5ee35eb9e72bc21af4eb",
  group: 0,
  page: 3,
  word: "represent",
  image: "files/04_0076.jpg",
  audio: "files/04_0076.mp3",
  audioMeaning: "files/04_0076_meaning.mp3",
  audioExample: "files/04_0076_example.mp3",
  textMeaning: "To <i>represent</i> is to speak or act for a person or group.",
  textExample: "My lawyer will <b>represent</b> me in court.",
  transcription: "[rèprizént]",
  textExampleTranslate: "Мой адвокат будет представлять меня в суде",
  textMeaningTranslate: "Представлять - значит говорить или действовать от лица или группы",
  wordTranslate: "представлять"
  },
  {
  id: "5e9f5ee35eb9e72bc21af4ec",
  group: 0,
  page: 3,
  word: "shake",
  image: "files/04_0077.jpg",
  audio: "files/04_0077.mp3",
  audioMeaning: "files/04_0077_meaning.mp3",
  audioExample: "files/04_0077_example.mp3",
  textMeaning: "To <i>shake</i> is to move back and forth or up and down quickly.",
  textExample: "When people <b>shake</b> hands, it usually means they agree.",
  transcription: "[ʃeik]",
  textExampleTranslate: "Когда люди пожимают друг другу руки, это обычно означает, что они согласны",
  textMeaningTranslate: "Трясти - значит быстро двигаться вперед-назад или вверх-вниз",
  wordTranslate: "трясти"
  },
  {
  id: "5e9f5ee35eb9e72bc21af4ed",
  group: 0,
  page: 3,
  word: "spread",
  image: "files/04_0078.jpg",
  audio: "files/04_0078.mp3",
  audioMeaning: "files/04_0078_meaning.mp3",
  audioExample: "files/04_0078_example.mp3",
  textMeaning: "To <i>spread</i> is to move out to cover a larger area.",
  textExample: "I like to <b>spread</b> butter on my toast.",
  transcription: "[spred]",
  textExampleTranslate: "Мне нравится разливать масло по моему тосту",
  textMeaningTranslate: "Распространение означает выход на большую площадь",
  wordTranslate: "распространение"
  },
  {
  id: "5e9f5ee35eb9e72bc21af4ee",
  group: 0,
  page: 3,
  word: "stroll",
  image: "files/04_0079.jpg",
  audio: "files/04_0079.mp3",
  audioMeaning: "files/04_0079_meaning.mp3",
  audioExample: "files/04_0079_example.mp3",
  textMeaning: "To <i>stroll</i> means to walk slowly and calmly.",
  textExample: "My dog and I <b>strolled</b> through the park today.",
  transcription: "[stroul]",
  textExampleTranslate: "Сегодня мы с собакой прогулялись по парку",
  textMeaningTranslate: "Гулять значит ходить медленно и спокойно",
  wordTranslate: "прогулка"
  },
  {
  id: "5e9f5ee35eb9e72bc21af4ef",
  group: 0,
  page: 3,
  word: "village",
  image: "files/04_0080.jpg",
  audio: "files/04_0080.mp3",
  audioMeaning: "files/04_0080_meaning.mp3",
  audioExample: "files/04_0080_example.mp3",
  textMeaning: "A <i>village</i> is a very small town.",
  textExample: "There are only a few houses in my <b>village</b>.",
  transcription: "[vílidʒ]",
  textExampleTranslate: "В моей деревне всего несколько домов",
  textMeaningTranslate: "Деревня очень маленький город",
  wordTranslate: "деревня"
  }
]